[04/Jun/2016 14:15:14] "GET /send_email/ HTTP/1.1" 200 7102
[04/Jun/2016 14:15:14] "GET /static/css/styles.css HTTP/1.1" 304 0
[04/Jun/2016 14:15:14] "GET /static/css/view.css HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/css/animation.css HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/css/lrtk.css HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/js/jquery.js HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/js/jquery.cookie.js HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/js/js.js HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/js/duo-shuo.js HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/js/csrf.js HTTP/1.1" 304 0
[04/Jun/2016 14:15:15] "GET /static/images/art.jpg HTTP/1.1" 304 0
[04/Jun/2016 14:15:16] "GET /static/images/favicon.ico HTTP/1.1" 200 2462
[04/Jun/2016 14:15:20] "GET / HTTP/1.1" 200 9361
[04/Jun/2016 14:16:49] "GET / HTTP/1.1" 200 9361
Not Found: /http:/check.best-proxies.ru/azenv.php
[04/Jun/2016 14:17:25] "POST http://check.best-proxies.ru/azenv.php?auth=146504984559&a=PSCN&i=1998452890&p=80 HTTP/1.1" 404 1775
[04/Jun/2016 14:18:28] "GET / HTTP/1.1" 200 9361
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[04/Jun/2016 14:37:31] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1729
Not Found: /smtp.mail.yahoo.com:25
[04/Jun/2016 15:27:30] "CONNECT smtp.mail.yahoo.com:25 HTTP/1.0" 404 1676
Not Found: /smtp.mail.yahoo.com:25
[04/Jun/2016 17:51:50] "CONNECT smtp.mail.yahoo.com:25 HTTP/1.0" 404 1676
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[04/Jun/2016 18:37:42] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1729
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[04/Jun/2016 18:41:14] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1729
Not Found: /http:/check.best-proxies.ru/azenv.php
[04/Jun/2016 19:09:08] "POST http://check.best-proxies.ru/azenv.php?auth=146506734849&a=PSCN&i=1998452890&p=80 HTTP/1.1" 404 1775
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[04/Jun/2016 19:13:27] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1729
Not Found: /smtp.mail.yahoo.com:25
[04/Jun/2016 19:23:24] "CONNECT smtp.mail.yahoo.com:25 HTTP/1.0" 404 1676
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Performing system checks...

System check identified no issues (0 silenced).
June 04, 2016 - 14:15:09
Django version 1.10a1, using settings 'my_blog.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
None
None
None
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 36815)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 55310)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 42127)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 56424)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 38644)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 50137)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 59147)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 34772)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 40768)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 47126)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 53515)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 51920)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 51683)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 51391)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 50237)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 50243)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 54317)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 51115)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 50773)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 49618)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 59847)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 37340)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 40156)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 37159)
----------------------------------------
------------------------Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/Django-1.10a1-py2.7.egg/django/core/servers/basehttp.py", line 159, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
[04/Jun/2016 20:34:23] "GET / HTTP/1.0" 200 9361
Not Found: /http:/www.baidu.com/
[04/Jun/2016 20:39:16] "GET http://www.baidu.com/ HTTP/1.1" 404 1660
Not Found: /s.yimg.com:443
[04/Jun/2016 20:58:59] "CONNECT s.yimg.com:443 HTTP/1.1" 404 1641
Not Found: /s.yimg.com:443
[04/Jun/2016 20:59:00] "CONNECT s.yimg.com:443 HTTP/1.1" 404 1641
Not Found: /l.yimg.com:80
[04/Jun/2016 20:59:00] "CONNECT l.yimg.com:80 HTTP/1.1" 404 1638
[04/Jun/2016 21:45:14] "GET / HTTP/1.1" 200 9361
Not Found: /http:/3gqq.qq.com/
[04/Jun/2016 22:12:27] "GET http://3gqq.qq.com/ HTTP/1.1" 404 1652
Not Found: /s.yimg.com:443
[04/Jun/2016 22:14:00] "CONNECT s.yimg.com:443 HTTP/1.1" 404 1641
Not Found: /s.yimg.com:443
[04/Jun/2016 22:14:00] "CONNECT s.yimg.com:443 HTTP/1.1" 404 1641
Not Found: /l.yimg.com:80
[04/Jun/2016 22:14:01] "CONNECT l.yimg.com:80 HTTP/1.1" 404 1638
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[04/Jun/2016 22:39:22] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1729
Not Found: /smtp.mail.yahoo.com:25
[04/Jun/2016 22:42:15] "CONNECT smtp.mail.yahoo.com:25 HTTP/1.0" 404 1676
[04/Jun/2016 23:04:00] "GET / HTTP/1.1" 200 9361
Not Found: /smtp.mail.yahoo.com:25
[04/Jun/2016 23:18:35] "CONNECT smtp.mail.yahoo.com:25 HTTP/1.0" 404 1676
Not Found: /s.yimg.com:443
[04/Jun/2016 23:30:14] "CONNECT s.yimg.com:443 HTTP/1.1" 404 1641
Not Found: /s.yimg.com:443
[04/Jun/2016 23:30:15] "CONNECT s.yimg.com:443 HTTP/1.1" 404 1641
Not Found: /l.yimg.com:80
[04/Jun/2016 23:30:15] "CONNECT l.yimg.com:80 HTTP/1.1" 404 1638
Not Found: /smtp.mail.yahoo.com:25
[04/Jun/2016 23:42:04] "CONNECT smtp.mail.yahoo.com:25 HTTP/1.0" 404 1676
Not Found: /http:/check.best-proxies.ru/azenv.php
[04/Jun/2016 23:57:11] "POST http://check.best-proxies.ru/azenv.php?auth=146508463137&a=PSCN&i=1998452890&p=80 HTTP/1.1" 404 1775
Not Found: /http:/www.jd.com/
[04/Jun/2016 23:57:17] "GET http://www.jd.com/ HTTP/1.1" 404 1648
Not Found: /www.google.com:443
[04/Jun/2016 23:57:17] "CONNECT www.google.com:443 HTTP/1.0" 404 1664
[05/Jun/2016 00:57:52] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\xad\x01\x00\x00\xa9\x03\x01WSx')
[05/Jun/2016 00:57:52] You're accessing the development server over HTTPS, but it only supports HTTP.

[05/Jun/2016 00:57:52] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x00\xad\x01\x00\x00\xa9\x03\x01WSx!V\x8b')
[05/Jun/2016 00:57:52] You're accessing the development server over HTTPS, but it only supports HTTP.

Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[05/Jun/2016 01:42:13] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1729
----------------
Exception happened during processing of request from ('113.108.0.27', 60617)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 56639)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 47641)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 41233)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 33879)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 52976)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 36808)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 48807)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 58548)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 43091)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 53099)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 34742)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 39511)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 46065)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 51997)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('113.108.0.27', 56594)
----------------------------------------
Performing system checks...

System check identified no issues (0 silenced).
June 05, 2016 - 02:27:57
Django version 1.10a1, using settings 'my_blog.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Not Found: /smtp.mail.yahoo.com:25
[05/Jun/2016 02:32:59] "CONNECT smtp.mail.yahoo.com:25 HTTP/1.0" 404 1676
Performing system checks...

System check identified no issues (0 silenced).
June 05, 2016 - 02:29:50
Django version 1.10a1, using settings 'my_blog.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
June 05, 2016 - 02:33:11
Django version 1.10a1, using settings 'my_blog.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
